version: '3'
services:
  blog:
    image: tianon/github-pages
    command: ["jekyll", "serve", "--host", "0.0.0.0", "--force_polling", "--livereload"]
    ports:
    - "4000:4000"
    - "35729:35729"
    volumes:
    - .:/blog
    environment: 
    - JEKYLL_ENV=preview